hydra:
  run:
    dir: /Users/nicholasworley/projects/rembler/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - train_spec: train_spec


random_state:
  random_seed: 22

experiment: 
  experiment_name: default_experiment