train_data: null
val_data: null
output_dir: Path
epochs: 25
batch_size: 64
learning_rate: .0003
weight_decay: .0001
grad_clip: 1.0
num_workers: 0
device: "auto"
seed: 42
log_interval: 48
checkpoint_name: "best.pt"
model_type: "small_cnn"  # "small_cnn", "cnn_bilstm", "implicit_cnn"